### ISSUE TITLE
Windows-specific issues

### ISSUE THREAD

**Issue by cournape** [enthought/encore#107]
I see those test errors on windows on 3.5:

```
[172.17.5.161] err: ======================================================================
[172.17.5.161] err: ERROR: test_acquire (encore.storage.tests.test_file_lock.FileLockTest)
[172.17.5.161] err: ----------------------------------------------------------------------
[172.17.5.161] err: Traceback (most recent call last):
[172.17.5.161] err:   File "C:\Users\vagrant\.edm-build\envs\build-env\lib\site-packages\encore\storage\tests\test_file_lock.py", line 41, in tearDown
[172.17.5.161] err:     os.remove(self.path)
[172.17.5.161] err: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\vagrant\\AppData\\Local\\Temp\\tmpswpzuzrvshare'
[172.17.5.161] err: 
[172.17.5.161] err: ======================================================================
[172.17.5.161] err: ERROR: test_acquired (encore.storage.tests.test_file_lock.FileLockTest)
[172.17.5.161] err: ----------------------------------------------------------------------
[172.17.5.161] err: Traceback (most recent call last):
[172.17.5.161] err:   File "C:\Users\vagrant\.edm-build\envs\build-env\lib\site-packages\encore\storage\tests\test_file_lock.py", line 41, in tearDown
[172.17.5.161] err:     os.remove(self.path)
[172.17.5.161] err: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\vagrant\\AppData\\Local\\Temp\\tmp5ui9w_bmshare'
[172.17.5.161] err: 
[172.17.5.161] err: ======================================================================
[172.17.5.161] err: ERROR: test_data (encore.storage.tests.test_file_lock.FileLockTest)
[172.17.5.161] err: ----------------------------------------------------------------------
[172.17.5.161] err: Traceback (most recent call last):
[172.17.5.161] err:   File "C:\Users\vagrant\.edm-build\envs\build-env\lib\site-packages\encore\storage\tests\test_file_lock.py", line 41, in tearDown
[172.17.5.161] err:     os.remove(self.path)
[172.17.5.161] err: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\vagrant\\AppData\\Local\\Temp\\tmpoejgh4vvshare'
[172.17.5.161] err: 
[172.17.5.161] err: ======================================================================
[172.17.5.161] err: ERROR: test_force_timeout (encore.storage.tests.test_file_lock.FileLockTest)
[172.17.5.161] err: ----------------------------------------------------------------------
[172.17.5.161] err: Traceback (most recent call last):
[172.17.5.161] err:   File "C:\Users\vagrant\.edm-build\envs\build-env\lib\site-packages\encore\storage\tests\test_file_lock.py", line 41, in tearDown
[172.17.5.161] err:     os.remove(self.path)
[172.17.5.161] err: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\vagrant\\AppData\\Local\\Temp\\tmpb88a20washare'
[172.17.5.161] err: 
[172.17.5.161] err: ======================================================================
[172.17.5.161] err: ERROR: test_release (encore.storage.tests.test_file_lock.FileLockTest)
[172.17.5.161] err: ----------------------------------------------------------------------
[172.17.5.161] err: Traceback (most recent call last):
[172.17.5.161] err:   File "C:\Users\vagrant\.edm-build\envs\build-env\lib\site-packages\encore\storage\tests\test_file_lock.py", line 41, in tearDown
[172.17.5.161] err:     os.remove(self.path)
[172.17.5.161] err: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\vagrant\\AppData\\Local\\Temp\\tmp5koj5ulashare'
[172.17.5.161] err: 
[172.17.5.161] err: ======================================================================
[172.17.5.161] err: FAIL: test_events_delayed (encore.concurrent.futures.tests.test_delayed_asynchronizer.TestAsynchronizer)
[172.17.5.161] err: ----------------------------------------------------------------------
[172.17.5.161] err: Traceback (most recent call last):
[172.17.5.161] err:   File "C:\Users\vagrant\.edm-build\envs\build-env\lib\site-packages\encore\concurrent\futures\tests\test_delayed_asynchronizer.py", line 122, in test_events_delayed
[172.17.5.161] err:     self.assertGreaterEqual(difference, 0.5)
[172.17.5.161] err: AssertionError: 0.4999678134918213 not greater than or equal to 0.5
```

**Comment by dpinte** [comment]
Would have been spotted if #103 was solved... I'll look at it asap but not today. @cournape Not sure we should consider the failure and errors as blocker though
